In [77]:
import pandas as pd
from tqdm import tqdm
import numpy as np
from sklearn.model_selection import train_test_split

### float자리에 dict있는 데이터 제거

In [66]:
data = pd.read_json('tyk2.json', lines=True)
data

,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0se,AATS0v,...,piPC5,piPC6,piPC7,piPC8,piPC9,pyrimidine,quinazoline,smile_ft,smiles,subset
0,24.512821,6.340377,3.846154,8.974359,163.171956,97.910428,1.587114,6.407277,7.773880,237.026191,...,6.738041,7.355032,7.929636,8.497942,8.953173,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC(C)(C)C1=NC2=C(N1)C3=C(C=C(C=C3)F)C4=C2C=CNC4=O,10
1,26.829268,6.070571,3.219512,6.342066,164.769028,107.248642,1.524555,6.164744,7.649270,212.219226,...,6.139750,6.327714,6.685197,7.026177,7.376469,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC(C)S(=O)(=O)C1=CC=CC=C1NC2=NC(=NC=C2Cl)NC3=C...,10
2,22.885714,6.094274,3.685714,7.800000,162.193234,90.402944,1.573107,6.179199,7.575353,231.777721,...,7.064893,7.630803,8.253616,8.865921,9.369196,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC1=C(C(=CC=C1)C)N2C(=O)C3=CN=C(N=C3N4C2=NC5=C...,10
3,23.098039,6.285182,3.470588,7.764706,166.897682,91.170512,1.430816,6.337763,7.762929,213.680942,...,5.971102,6.429694,6.921219,7.392900,7.665589,0,0,"[0, 0, 1, 0, 0, 0.0, 0.25, 0.0, 0.25, 0, 0, 0,...",C1CC1NC(=O)NC2=C(NN=C2)C3=NC4=C(N3)C=C(C=C4)CN...,10
4,24.657143,6.496493,3.514286,9.085714,166.987500,99.059140,1.503893,6.538163,7.906872,225.978626,...,6.467213,6.803540,7.235326,7.656696,8.102889,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC1=C(C=C(C=C1)C(=O)NC2=C(C=CC(=C2)C(F)(F)F)OC...,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,23.263158,6.225868,3.491228,7.964912,162.781755,91.870610,1.509273,6.294189,7.719251,224.688464,...,5.765583,5.930918,6.283434,6.683283,6.990832,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1534,23.263158,6.225868,3.491228,7.964912,162.781755,91.870610,1.509273,6.294189,7.719251,224.688464,...,5.765583,5.930918,6.283434,6.683283,6.990832,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1535,23.892857,6.307311,3.571429,8.357143,163.894430,94.420368,1.500090,6.369070,7.784642,224.927785,...,5.759296,5.930918,6.282500,6.686407,6.979611,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1536,22.508475,6.178890,3.406780,7.525424,163.532124,88.790795,1.473182,6.244895,7.685326,218.125592,...,5.749791,5.906723,6.252145,6.639140,6.938042,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CCOCC2=NC(=CC=C2)NC3=NC=CC(=C3)N4C[C@@H](COC...,10
1537,23.219512,6.241937,3.609756,8.048780,166.100466,91.699009,1.476308,6.303493,7.710784,219.806186,...,5.640576,5.948891,6.325660,6.668491,6.674714,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",C[C@H]1CN([C@]12CCN(C2)C3=NC=NC4=C3C=CN4)C(=O)...,10

In [67]:
err_idx = []
for i in tqdm(range(len(data))):
    try: 
        data.drop(columns=['smile_ft', 'id', 'subset', 'quinazoline', 'pyrimidine', 'smiles', 'active']).iloc[i,:].astype(np.float64)
    except:
        err_idx.append(i)

100%|█████████████████████████████████████████████████████████████████████████████| 1538/1538 [00:10<00:00, 147.30it/s]

In [68]:
err_idx

[]

In [69]:
data.select_dtypes(object).columns

Index(['smile_ft', 'smiles'], dtype='object')

In [70]:
data.loc[err_idx, ['AXp-0dv', 'MDEC-33', 'Xp-0dv']]

Empty DataFrame
Columns: [AXp-0dv, MDEC-33, Xp-0dv]
Index: []

### smile_ft max_len 설정

In [71]:
data = data.drop(err_idx)

In [72]:
l = []
for i in data['smile_ft']:
    l.append(len(i))
pd.Series(l).value_counts()

6300    1532
7980       1
8358       1
8106       1
8610       1
6804       1
6930       1
dtype: int64

In [73]:
max_len = 6300
for i in tqdm(range(len(data))):
    data.iat[i, 866] = data.iloc[i, 866][:max_len]

### Train / Test split

In [76]:
data

,AATS0Z,AATS0are,AATS0d,AATS0dv,AATS0i,AATS0m,AATS0p,AATS0pe,AATS0se,AATS0v,...,piPC5,piPC6,piPC7,piPC8,piPC9,pyrimidine,quinazoline,smile_ft,smiles,subset
0,24.512821,6.340377,3.846154,8.974359,163.171956,97.910428,1.587114,6.407277,7.773880,237.026191,...,6.738041,7.355032,7.929636,8.497942,8.953173,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC(C)(C)C1=NC2=C(N1)C3=C(C=C(C=C3)F)C4=C2C=CNC4=O,10
1,26.829268,6.070571,3.219512,6.342066,164.769028,107.248642,1.524555,6.164744,7.649270,212.219226,...,6.139750,6.327714,6.685197,7.026177,7.376469,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC(C)S(=O)(=O)C1=CC=CC=C1NC2=NC(=NC=C2Cl)NC3=C...,10
2,22.885714,6.094274,3.685714,7.800000,162.193234,90.402944,1.573107,6.179199,7.575353,231.777721,...,7.064893,7.630803,8.253616,8.865921,9.369196,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC1=C(C(=CC=C1)C)N2C(=O)C3=CN=C(N=C3N4C2=NC5=C...,10
3,23.098039,6.285182,3.470588,7.764706,166.897682,91.170512,1.430816,6.337763,7.762929,213.680942,...,5.971102,6.429694,6.921219,7.392900,7.665589,0,0,"[0, 0, 1, 0, 0, 0.0, 0.25, 0.0, 0.25, 0, 0, 0,...",C1CC1NC(=O)NC2=C(NN=C2)C3=NC4=C(N3)C=C(C=C4)CN...,10
4,24.657143,6.496493,3.514286,9.085714,166.987500,99.059140,1.503893,6.538163,7.906872,225.978626,...,6.467213,6.803540,7.235326,7.656696,8.102889,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",CC1=C(C=C(C=C1)C(=O)NC2=C(C=CC(=C2)C(F)(F)F)OC...,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1533,23.263158,6.225868,3.491228,7.964912,162.781755,91.870610,1.509273,6.294189,7.719251,224.688464,...,5.765583,5.930918,6.283434,6.683283,6.990832,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1534,23.263158,6.225868,3.491228,7.964912,162.781755,91.870610,1.509273,6.294189,7.719251,224.688464,...,5.765583,5.930918,6.283434,6.683283,6.990832,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1535,23.892857,6.307311,3.571429,8.357143,163.894430,94.420368,1.500090,6.369070,7.784642,224.927785,...,5.759296,5.930918,6.282500,6.686407,6.979611,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CC1[C@@]2([C@H]3CN(C2=O)C4=CC(=NC=C4)NC5=CC=...,10
1536,22.508475,6.178890,3.406780,7.525424,163.532124,88.790795,1.473182,6.244895,7.685326,218.125592,...,5.749791,5.906723,6.252145,6.639140,6.938042,0,0,"[0, 0, 0, 1, 0, 0.0, 0.25, 0.0, 0.375, 0, 0, 0...",C1CCOCC2=NC(=CC=C2)NC3=NC=CC(=C3)N4C[C@@H](COC...,10
1537,23.219512,6.241937,3.609756,8.048780,166.100466,91.699009,1.476308,6.303493,7.710784,219.806186,...,5.640576,5.948891,6.325660,6.668491,6.674714,0,0,"[0, 1, 0, 0, 0, 0.375, 1.0, 0.0, 0.5, 0, 0, 0,...",C[C@H]1CN([C@]12CCN(C2)C3=NC=NC4=C3C=CN4)C(=O)...,10

In [78]:
train, test = train_test_split(data, shuffle=True, test_size=0.2, random_state=42)

In [81]:
train.to_json('tyk2.json',orient='records', lines=True)
test.to_json('tyk2_test.json',orient='records', lines=True)